exo_pets_homepage:
    path:     /pets/all
    defaults: { _controller: ExoPetsBundle:Default:index }
exo_pets_voir:
    path:    /pets/voir/{id}
    defaults: { _controller: ExoPetsBundle:Default:voir }
exo_pets_ajouter:
    path:     /pets/ajouter/{nom}/{poids}
    defaults: { _controller: ExoPetsBundle:Default:ajouter }
exo_pets_ajouter2:
    path:     /pets/animal/ajouter
    defaults: { _controller: ExoPetsBundle:Default:ajouter2 }
exo_pets_ajouter3:
    path:     /pets/animal/ajouter3
    defaults: { _controller: ExoPetsBundle:Default:ajouter3 }

exo_pets_update:
    path: /pets/update/{id}
    defaults: { _controller: ExoPetsBundle:Default:update }

exo_pets_delete:
    path: /pets/delete/{id}
    defaults: { _controller: ExoPetsBundle:Default:delete }

exo_pets_findLourd:
    path: /pets/lourd/{poids}
    defaults: { _controller: ExoPetsBundle:Default:lourd }

exo_pets_substring:
    path: /pets/souschaine/{souschaine}
    defaults: { _controller: ExoPetsBundle:Default:substring }

exo_pets_poidsmin:
    path: /pets/poidsmin
    defaults: { _controller: ExoPetsBundle:Default:poidsmin }

exo_pets_doubler:
    path: /pets/double
    defaults: { _controller: ExoPetsBundle:Default:doubler }

exo_pets_maitre:
    path: /pets/maitre/voirTout/{id}
    defaults: { _controller: ExoPetsBundle:Default:voirTout }